# Generated by Django 3.0.4 on 2020-03-11 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('alcohol', 'alcohol'), ('bread', 'bread'), ('children', 'children'), ('cloths', 'cloths'), ('dairy', 'dairy'), ('drinks', 'drinks'), ('home', 'home'), ('household_chemistry', 'household_chemistry'), ('hygiene', 'hygiene'), ('meats and fishes', 'meat and fishes'), ('others', 'others'), ('sweets', 'sweets'), ('vegetables and fruits', 'vegetables and fruits')], max_length=64)),
                ('unit', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('add_date', models.DateField(auto_now=True)),
                ('description', models.TextField(verbose_name='steps')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('create_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingListProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ShoppingList')),
            ],
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='products',
            field=models.ManyToManyField(related_name='shopping_list', through='backend.ShoppingListProducts', to='backend.Product'),
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe', through='backend.RecipeIngredients', to='backend.Product'),
        ),
    ]
