# Generated by Django 3.0.4 on 2020-03-12 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('alcohol', 'alcohol'), ('bread', 'bread'), ('concentrates', 'concentrates'), ('dairy', 'dairy'), ('drinks and liquids', 'drinks and liquids'), ('meats and fishes', 'meat and fishes'), ('others', 'others'), ('powdered products', 'powdered products'), ('spices', 'spices'), ('sweets', 'sweets'), ('vegetables and fruits', 'vegetables and fruits')], max_length=64),
        ),
    ]
